-- Create Blueline Database
CREATE DATABASE IF NOT EXISTS shield;
USE shield;

-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
  `id` VARCHAR(36) PRIMARY KEY,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255),
  `profilePictureUrl` TEXT,
  `displayName` VARCHAR(100),
  `passwordHash` VARCHAR(255),
  `role` VARCHAR(20) NOT NULL DEFAULT 'user',
  `receivesMessages` BOOLEAN DEFAULT 1,
  `appScale` VARCHAR(20) NOT NULL DEFAULT 'comfortable',
  `twoFactorSecret` VARCHAR(64),
  `twoFactorEnabled` BOOLEAN DEFAULT 0,
  `peNumber` VARCHAR(50) UNIQUE,
  `peopleSoftId` VARCHAR(50),
  `carNumber` VARCHAR(50),
  `badgeNumber` VARCHAR(50) UNIQUE,
  `radioNumber` VARCHAR(50),
  `personalPhoneNumber` TEXT,
  `personalPhoneNumberHash` VARCHAR(64),
  `departmentPhoneNumber` VARCHAR(50),
  `assignedTo` VARCHAR(100),
  `district` VARCHAR(100),
  `rank` VARCHAR(100),
  `isActive` BOOLEAN DEFAULT 1,
  `employmentType` VARCHAR(100),
  `typeDetails` VARCHAR(255),
  `status` VARCHAR(100),
  `supervisor` VARCHAR(100),
  `specialtyCertifications` TEXT,
  `publicSafetyId` VARCHAR(50) UNIQUE,
  `race` VARCHAR(50),
  `sex` VARCHAR(10),
  `maritalStatus` VARCHAR(50),
  `residentialAddress` TEXT,
  `mailingAddress` TEXT,
  `emergencyContactName` VARCHAR(150),
  `emergencyContactRelationship` VARCHAR(100),
  `emergencyContactPhone` TEXT,
  `emergencyContactPhoneHash` VARCHAR(64),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_firstName` (`firstName`),
  INDEX `idx_lastName` (`lastName`),
  INDEX `idx_peNumber` (`peNumber`),
  INDEX `idx_badgeNumber` (`badgeNumber`),
  INDEX `idx_publicSafetyId` (`publicSafetyId`),
  INDEX `idx_rank` (`rank`),
  INDEX `idx_district` (`district`),
  INDEX `idx_isActive` (`isActive`),
  INDEX `idx_employmentType` (`employmentType`),
  INDEX `idx_user_email` (`email`),
  INDEX `idx_user_role` (`role`),
  INDEX `idx_users_active_district` (`isActive`, `district`),
  INDEX `idx_users_name` (`lastName`, `firstName`),
  INDEX `idx_users_people_soft` (`peopleSoftId`),
  INDEX `idx_users_radio` (`radioNumber`),
  INDEX `idx_users_personal_phone_hash` (`personalPhoneNumberHash`),
  INDEX `idx_users_emergency_phone_hash` (`emergencyContactPhoneHash`),
  FULLTEXT INDEX `ft_search` (`firstName`, `lastName`, `email`, `peNumber`, `peopleSoftId`, `badgeNumber`, `publicSafetyId`, `district`)
);

CREATE TABLE IF NOT EXISTS user_messages (
  `id` VARCHAR(36) PRIMARY KEY,
  `senderAccountId` VARCHAR(36) NOT NULL,
  `recipientUserId` VARCHAR(36) NOT NULL,
  `subject` VARCHAR(200) NOT NULL,
  `body` TEXT NOT NULL,
  `isRead` BOOLEAN DEFAULT 0,
  `isArchived` BOOLEAN DEFAULT 0,
  `senderDeleted` BOOLEAN DEFAULT 0,
  `recipientDeleted` BOOLEAN DEFAULT 0,
  `senderReaction` VARCHAR(30),
  `recipientReaction` VARCHAR(30),
  `threadId` VARCHAR(36),
  `threadType` VARCHAR(30) DEFAULT 'direct',
  `threadTitle` VARCHAR(200),
  `threadParticipantIds` TEXT,
  `threadParticipantNames` TEXT,
  `groupMessageId` VARCHAR(36),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_messages_sender` (`senderAccountId`),
  INDEX `idx_messages_recipient` (`recipientUserId`),
  INDEX `idx_messages_sender_created` (`senderAccountId`, `createdAt`),
  INDEX `idx_messages_recipient_read_created` (`recipientUserId`, `isRead`, `createdAt`),
  INDEX `idx_messages_group_thread_created` (`threadId`, `createdAt`),
  INDEX `idx_messages_inbox_cursor` (`recipientUserId`, `recipientDeleted`, `isArchived`, `createdAt`, `id`),
  INDEX `idx_messages_sent_cursor` (`senderAccountId`, `senderDeleted`, `createdAt`, `id`),
  INDEX `idx_messages_direct_out_cursor` (`senderAccountId`, `recipientUserId`, `senderDeleted`, `createdAt`, `id`),
  INDEX `idx_messages_direct_in_cursor` (`recipientUserId`, `senderAccountId`, `recipientDeleted`, `isArchived`, `createdAt`, `id`),
  INDEX `idx_messages_group_participant_cursor` (`threadId`, `senderAccountId`, `recipientUserId`, `createdAt`, `id`)
);

CREATE TABLE IF NOT EXISTS devices (
  `id` VARCHAR(36) PRIMARY KEY,
  `type` VARCHAR(50) NOT NULL,
  `assetTag` VARCHAR(100) NOT NULL UNIQUE,
  `makeModel` VARCHAR(150) NOT NULL,
  `serialNumber` VARCHAR(150),
  `assignedTo` VARCHAR(150),
  `status` VARCHAR(50) NOT NULL DEFAULT 'Available',
  `carrier` VARCHAR(50) NOT NULL DEFAULT 'Verizon',
  `location` VARCHAR(150),
  `notes` TEXT,
  `phoneNumber` VARCHAR(50),
  `imei` VARCHAR(100),
  `simNumber` VARCHAR(100),
  `radioId` VARCHAR(100),
  `hostname` VARCHAR(150),
  `routerId` VARCHAR(150),
  `warrantyExpiration` DATE,
  `replacementDueDate` DATE,
  `maintenanceDueDate` DATE,
  `lastServiceDate` DATE,
  `purchaseDate` DATE,
  `condition` VARCHAR(50) NOT NULL DEFAULT 'Good',
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_devices_type` (`type`),
  INDEX `idx_devices_status` (`status`),
  INDEX `idx_devices_updated_asset` (`updatedAt`, `assetTag`),
  INDEX `idx_devices_assigned_updated` (`assignedTo`, `updatedAt`, `assetTag`),
  INDEX `idx_devices_type_updated_asset` (`type`, `updatedAt`, `assetTag`),
  INDEX `idx_devices_status_updated_asset` (`status`, `updatedAt`, `assetTag`),
  INDEX `idx_devices_carrier_updated_asset` (`carrier`, `updatedAt`, `assetTag`),
  INDEX `idx_devices_model_updated_asset` (`makeModel`, `updatedAt`, `assetTag`),
  INDEX `idx_devices_type_status` (`type`, `status`),
  INDEX `idx_devices_carrier_type_model` (`carrier`, `type`, `makeModel`),
  INDEX `idx_devices_condition` (`condition`)
);

CREATE TABLE IF NOT EXISTS device_events (
  `id` VARCHAR(36) PRIMARY KEY,
  `deviceId` VARCHAR(36) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `actorId` VARCHAR(36),
  `actorName` VARCHAR(150),
  `assignedTo` VARCHAR(150),
  `status` VARCHAR(50),
  `notes` TEXT,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `idx_device_events_device` (`deviceId`),
  INDEX `idx_device_events_created` (`createdAt`),
  INDEX `idx_device_events_device_created` (`deviceId`, `createdAt`)
);

-- Sample Data (Optional)
INSERT INTO users (
  `id`, `firstName`, `lastName`, `peNumber`, `carNumber`, `badgeNumber`,
  `assignedTo`, `district`, `rank`, `isActive`, `employmentType`, `typeDetails`,
  `status`, `supervisor`, `specialtyCertifications`, `publicSafetyId`, `race`, `sex`
) VALUES
  (UUID(), 'John', 'Smith', 'PE001', 'CAR001', 'BADGE001', 'Precinct A', 'District 1', 'Officer', 1, 'Full-time', 'Patrol', 'Active', 'Captain Davis', 'CPR Certified', 'PSID001', 'Caucasian', 'M'),
  (UUID(), 'Sarah', 'Johnson', 'PE002', 'CAR002', 'BADGE002', 'Precinct B', 'District 2', 'Detective', 1, 'Full-time', 'Investigation', 'Active', 'Captain Rodriguez', 'Advanced Investigation', 'PSID002', 'African American', 'F'),
  (UUID(), 'Michael', 'Williams', 'PE003', 'CAR003', 'BADGE003', 'Precinct A', 'District 1', 'Officer', 1, 'Full-time', 'Patrol', 'Active', 'Captain Davis', 'K9 Handler', 'PSID003', 'Hispanic', 'M');
