import { Router } from 'express';
import { AuthController } from '../controllers/authController';
import { requireAnyPermission, requirePermission, requireSelfOrPermission } from '../middleware/permissions';
import { rateLimit } from '../middleware/rateLimit';

const router = Router();
const authLimiter = rateLimit({ keyPrefix: 'auth', windowMs: 15 * 60 * 1000, max: 30, message: 'Too many auth attempts. Try again later.' });
const inviteLimiter = rateLimit({ keyPrefix: 'invite', windowMs: 15 * 60 * 1000, max: 20, message: 'Too many invite attempts. Try again later.' });
const passwordResetLimiter = rateLimit({ keyPrefix: 'password-reset', windowMs: 15 * 60 * 1000, max: 10, message: 'Too many password reset attempts. Try again later.' });

router.post('/register', authLimiter, AuthController.register);
router.post('/login', authLimiter, AuthController.login);
router.get('/microsoft/status', AuthController.getMicrosoftSsoStatus);
router.get('/microsoft/start', authLimiter, AuthController.startMicrosoftSso);
router.get('/microsoft/callback', authLimiter, AuthController.completeMicrosoftSso);
router.post('/password-reset/request', passwordResetLimiter, AuthController.requestPasswordReset);
router.post('/password-reset/confirm', passwordResetLimiter, AuthController.resetPassword);
router.get('/session', AuthController.getSession);
router.post('/logout', AuthController.logout);
router.get('/registration-settings', AuthController.getRegistrationSettings);
router.put('/registration-settings', requirePermission('roles:manage'), AuthController.updateRegistrationSettings);
router.get('/invites', requirePermission('roles:manage'), AuthController.listInvites);
router.post('/invites', inviteLimiter, requirePermission('roles:manage'), AuthController.createInvite);
router.get('/sessions', AuthController.listSessions);
router.delete('/sessions/:sessionId', AuthController.revokeSession);
router.post('/sessions/revoke-others', AuthController.revokeOtherSessions);
router.post('/change-password', requireSelfOrPermission((req) => req.body?.accountId, 'roles:manage'), AuthController.changePassword);
router.post('/2fa/setup', requireSelfOrPermission((req) => req.body?.accountId, 'roles:manage'), AuthController.setupTwoFactor);
router.post('/2fa/enable', requireSelfOrPermission((req) => req.body?.accountId, 'roles:manage'), AuthController.enableTwoFactor);
router.post('/2fa/disable', requireSelfOrPermission((req) => req.body?.accountId, 'roles:manage'), AuthController.disableTwoFactor);
router.get('/accounts', requireAnyPermission(['roles:manage', 'devices:manage', 'reports:cpar']), AuthController.listAccounts);
router.put('/accounts/:accountId/role', requirePermission('roles:manage'), AuthController.updateRole);
router.put('/accounts/:accountId/message-preferences', requireSelfOrPermission((req) => req.params.accountId, 'roles:manage'), AuthController.updateMessagePreferences);
router.put('/accounts/:accountId/trooper-daily-preferences', requireSelfOrPermission((req) => req.params.accountId, 'roles:manage'), AuthController.updateTrooperDailyPreferences);
router.put('/accounts/:accountId/onboarding-complete', requireSelfOrPermission((req) => req.params.accountId, 'roles:manage'), AuthController.completeOnboarding);
router.get('/roles', requirePermission('roles:manage'), AuthController.listRoles);
router.post('/roles', requirePermission('roles:manage'), AuthController.createRole);
router.put('/roles/:roleId', requirePermission('roles:manage'), AuthController.updateRoleDefinition);

export default router;
