import { PerformanceEvaluation } from '../services/api';

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 42;
const ACCENT = '0.612 0.525 0.361';
const PRIMARY = '0.071 0.161 0.302';
const TEXT = '0.125 0.125 0.125';
const MUTED = '0.42 0.42 0.42';
const BORDER = '0.84 0.84 0.84';

const ratingLabels: Array<[string, string]> = [
  ['jobKnowledge', 'Job Knowledge'],
  ['qualityOfWork', 'Quality of Work'],
  ['productivity', 'Productivity'],
  ['communication', 'Communication'],
  ['teamwork', 'Teamwork'],
  ['reliability', 'Reliability'],
  ['leadership', 'Leadership'],
  ['policyCompliance', 'Policy Compliance'],
];

interface PdfPage {
  commands: string[];
  pageNumber: number;
}

function escapePdfText(value: unknown) {
  return String(value ?? '')
    .replace(/\\/gu, '\\\\')
    .replace(/\(/gu, '\\(')
    .replace(/\)/gu, '\\)')
    .replace(/\r?\n/gu, ' ');
}

function dateText(value: string | null) {
  return value ? new Date(value).toLocaleString() : 'Not recorded';
}

function cleanFilePart(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, '') || 'evaluation';
}

function wrapText(value: unknown, maxChars: number) {
  const text = String(value || 'Not recorded').replace(/\s+/gu, ' ').trim();
  const words = text.split(' ');
  const lines: string[] = [];
  let line = '';

  words.forEach((word) => {
    const nextLine = line ? `${line} ${word}` : word;
    if (nextLine.length > maxChars && line) {
      lines.push(line);
      line = word;
    } else {
      line = nextLine;
    }
  });

  if (line) {
    lines.push(line);
  }

  return lines.length > 0 ? lines : ['Not recorded'];
}

function rect(x: number, y: number, width: number, height: number, strokeColor = BORDER, fillColor?: string) {
  const fill = fillColor ? `${fillColor} rg ${x} ${y} ${width} ${height} re f` : '';
  return `${fill} ${strokeColor} RG 0.75 w ${x} ${y} ${width} ${height} re S`;
}

function line(x1: number, y1: number, x2: number, y2: number, color = BORDER, width = 0.5) {
  return `${color} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S`;
}

function textLine(x: number, y: number, text: string, size = 10, font = 'F1', color = TEXT) {
  return `BT /${font} ${size} Tf ${color} rg ${x} ${y} Td (${escapePdfText(text)}) Tj ET`;
}

function newPage(pageNumber: number): PdfPage {
  return { commands: [], pageNumber };
}

function addHeader(page: PdfPage, title: string, subtitle: string) {
  page.commands.push(`${PRIMARY} rg 0 ${PAGE_HEIGHT - 92} ${PAGE_WIDTH} 92 re f`);
  page.commands.push(`${ACCENT} rg 0 ${PAGE_HEIGHT - 92} 8 92 re f`);
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 45, 'SHIELD', 11, 'F2', '1 1 1'));
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 68, title, 20, 'F2', '1 1 1'));
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 84, subtitle, 9, 'F1', '0.86 0.9 0.95'));
}

function addFooter(page: PdfPage, totalPages: number) {
  page.commands.push(line(MARGIN, 34, PAGE_WIDTH - MARGIN, 34));
  page.commands.push(textLine(MARGIN, 20, 'Generated by SHIELD', 8, 'F1', MUTED));
  page.commands.push(textLine(PAGE_WIDTH - MARGIN - 56, 20, `Page ${page.pageNumber} of ${totalPages}`, 8, 'F1', MUTED));
}

function addField(page: PdfPage, x: number, y: number, width: number, label: string, value: unknown) {
  page.commands.push(rect(x, y - 42, width, 42, BORDER, '0.98 0.98 0.98'));
  page.commands.push(textLine(x + 9, y - 16, label.toUpperCase(), 7, 'F2', MUTED));
  page.commands.push(textLine(x + 9, y - 32, String(value || 'Not recorded').slice(0, 42), 10, 'F1', TEXT));
}

function addSection(page: PdfPage, x: number, y: number, width: number, title: string, value: unknown) {
  const lines = wrapText(value, 92);
  const height = Math.max(54, 30 + lines.length * 13);
  page.commands.push(rect(x, y - height, width, height));
  page.commands.push(`${ACCENT} rg ${x} ${y - 20} ${width} 20 re f`);
  page.commands.push(textLine(x + 10, y - 14, title, 9, 'F2', '1 1 1'));
  lines.forEach((line, index) => {
    page.commands.push(textLine(x + 10, y - 38 - index * 13, line, 9, 'F1', TEXT));
  });
  return y - height - 12;
}

function addRatingTable(page: PdfPage, evaluation: PerformanceEvaluation, y: number) {
  const x = MARGIN;
  const width = PAGE_WIDTH - MARGIN * 2;
  const rowHeight = 28;
  const labelWidth = 190;
  const rowsPerColumn = 4;
  page.commands.push(textLine(x, y, 'Ratings', 13, 'F2', PRIMARY));
  y -= 12;

  [0, 1].forEach((column) => {
    const columnX = x + column * (width / 2);
    const tableWidth = width / 2 - 8;
    page.commands.push(rect(columnX, y - rowHeight * rowsPerColumn, tableWidth, rowHeight * rowsPerColumn));
    ratingLabels.slice(column * rowsPerColumn, column * rowsPerColumn + rowsPerColumn).forEach(([key, label], index) => {
      const rowY = y - rowHeight * (index + 1);
      page.commands.push(index % 2 === 0 ? `0.98 0.98 0.98 rg ${columnX} ${rowY} ${tableWidth} ${rowHeight} re f` : '');
      page.commands.push(line(columnX, rowY, columnX + tableWidth, rowY));
      page.commands.push(textLine(columnX + 8, rowY + 9, label, 9, 'F1', TEXT));
      page.commands.push(textLine(columnX + labelWidth, rowY + 9, evaluation.ratings[key] || 'N/A', 10, 'F2', PRIMARY));
      page.commands.push(line(columnX + labelWidth - 10, rowY, columnX + labelWidth - 10, rowY + rowHeight));
    });
  });

  return y - rowHeight * rowsPerColumn - 24;
}

function addSignatureBox(page: PdfPage, x: number, y: number, width: number, title: string, signature: string, signedAt: string) {
  page.commands.push(rect(x, y - 74, width, 74));
  page.commands.push(textLine(x + 10, y - 17, title.toUpperCase(), 7, 'F2', MUTED));
  page.commands.push(textLine(x + 10, y - 43, signature || 'Awaiting signature', 18, 'F3', PRIMARY));
  page.commands.push(textLine(x + 10, y - 62, signedAt, 8, 'F1', MUTED));
}

function buildEvaluationPages(evaluation: PerformanceEvaluation, pageNumberStart: number, totalEvaluations: number, index: number) {
  const pages: PdfPage[] = [];
  let page = newPage(pageNumberStart);
  pages.push(page);
  addHeader(
    page,
    'Performance Evaluation',
    totalEvaluations > 1 ? `${evaluation.employeeName} (${index + 1} of ${totalEvaluations})` : evaluation.employeeName,
  );

  let y = PAGE_HEIGHT - 122;
  const fieldWidth = (PAGE_WIDTH - MARGIN * 2 - 12) / 2;
  addField(page, MARGIN, y, fieldWidth, 'Employee', evaluation.employeeName);
  addField(page, MARGIN + fieldWidth + 12, y, fieldWidth, 'Supervisor', evaluation.supervisorName);
  y -= 54;
  addField(page, MARGIN, y, fieldWidth, 'Evaluation Period', evaluation.evaluationPeriod);
  addField(page, MARGIN + fieldWidth + 12, y, fieldWidth, 'Status', evaluation.status);
  y -= 54;
  addField(page, MARGIN, y, fieldWidth, 'Position / Rank', evaluation.positionTitle);
  addField(page, MARGIN + fieldWidth + 12, y, fieldWidth, 'District / Unit', evaluation.district);
  y -= 58;

  y = addRatingTable(page, evaluation, y);
  y = addSection(page, MARGIN, y, PAGE_WIDTH - MARGIN * 2, 'Strengths', evaluation.strengths);
  y = addSection(page, MARGIN, y, PAGE_WIDTH - MARGIN * 2, 'Areas for Improvement', evaluation.improvements);

  page = newPage(pageNumberStart + pages.length);
  pages.push(page);
  addHeader(page, 'Performance Evaluation Continued', evaluation.employeeName);
  y = PAGE_HEIGHT - 122;
  y = addSection(page, MARGIN, y, PAGE_WIDTH - MARGIN * 2, 'Goals / Next Steps', evaluation.goals);
  y = addSection(page, MARGIN, y, PAGE_WIDTH - MARGIN * 2, 'Supervisor Comments', evaluation.supervisorComments);
  y = addSection(page, MARGIN, y, PAGE_WIDTH - MARGIN * 2, 'Employee Comments', evaluation.employeeComments);

  const boxWidth = (PAGE_WIDTH - MARGIN * 2 - 12) / 2;
  addSignatureBox(page, MARGIN, 140, boxWidth, 'Supervisor Signature', evaluation.supervisorSignature || evaluation.supervisorName, dateText(evaluation.supervisorSignedAt || evaluation.sentAt));
  addSignatureBox(page, MARGIN + boxWidth + 12, 140, boxWidth, 'Employee Signature', evaluation.employeeSignature, dateText(evaluation.employeeSignedAt));

  return pages;
}

function buildEmptyPage() {
  const page = newPage(1);
  addHeader(page, 'Performance Evaluations', 'No matching records');
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 140, 'No performance evaluations were found for this account or filter.', 11, 'F1', TEXT));
  return [page];
}

export function createPerformanceEvaluationPdf(evaluations: PerformanceEvaluation[]) {
  let pages = evaluations.length > 0
    ? evaluations.flatMap((evaluation, index, all) => buildEvaluationPages(evaluation, index * 2 + 1, all.length, index))
    : buildEmptyPage();

  pages = pages.map((page, index) => ({ ...page, pageNumber: index + 1 }));
  pages.forEach((page) => addFooter(page, pages.length));

  const objects: string[] = [];
  const addObject = (content: string) => {
    objects.push(content);
    return objects.length;
  };
  addObject('<< /Type /Catalog /Pages 2 0 R >>');
  const pagesId = addObject('');
  const fontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const boldFontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const italicFontId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Times-Italic >>');
  const pageObjectIds: number[] = [];

  pages.forEach((page) => {
    const stream = page.commands.filter(Boolean).join('\n');
    const contentId = addObject(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
    const pageId = addObject(
      `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontId} 0 R /F2 ${boldFontId} 0 R /F3 ${italicFontId} 0 R >> >> /Contents ${contentId} 0 R >>`,
    );
    pageObjectIds.push(pageId);
  });

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageObjectIds.length} >>`;

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return pdf;
}

export function downloadPerformanceEvaluationPdf(evaluations: PerformanceEvaluation[], filename = 'shield-performance-evaluations.pdf') {
  const safeFilename = filename.endsWith('.pdf') ? filename : `${cleanFilePart(filename)}.pdf`;
  const blob = new Blob([createPerformanceEvaluationPdf(evaluations)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = safeFilename;
  link.click();
  URL.revokeObjectURL(url);
}
