import { TrooperDailyReportEntry } from '../services/api';

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 42;
const PRIMARY = '0.071 0.161 0.302';
const ACCENT = '0.612 0.525 0.361';
const TEXT = '0.125 0.125 0.125';
const MUTED = '0.42 0.42 0.42';
const BORDER = '0.84 0.84 0.84';

interface PdfPage {
  commands: string[];
  pageNumber: number;
}

function cleanFilePart(value: string) {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, '') || 'trooper-dailies';
}

function userName(entry: TrooperDailyReportEntry) {
  return `${entry.user.firstName || ''} ${entry.user.lastName || ''}`.trim() || entry.user.email || 'Unknown';
}

function escapeCsv(value: unknown) {
  const text = String(value ?? '').replace(/\r?\n/gu, ' ');
  return /[",\n]/u.test(text) ? `"${text.replace(/"/gu, '""')}"` : text;
}

function downloadBlob(content: BlobPart, type: string, filename: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function escapePdfText(value: unknown) {
  return String(value ?? '')
    .replace(/\\/gu, '\\\\')
    .replace(/\(/gu, '\\(')
    .replace(/\)/gu, '\\)')
    .replace(/\r?\n/gu, ' ');
}

function textLine(x: number, y: number, text: string, size = 9, font = 'F1', color = TEXT) {
  return `BT /${font} ${size} Tf ${color} rg ${x} ${y} Td (${escapePdfText(text)}) Tj ET`;
}

function line(x1: number, y1: number, x2: number, y2: number, color = BORDER, width = 0.5) {
  return `${color} RG ${width} w ${x1} ${y1} m ${x2} ${y2} l S`;
}

function newPage(pageNumber: number): PdfPage {
  return { commands: [], pageNumber };
}

function addHeader(page: PdfPage, title: string, subtitle: string) {
  page.commands.push(`${PRIMARY} rg 0 ${PAGE_HEIGHT - 82} ${PAGE_WIDTH} 82 re f`);
  page.commands.push(`${ACCENT} rg 0 ${PAGE_HEIGHT - 82} 8 82 re f`);
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 38, 'SHIELD', 10, 'F2', '1 1 1'));
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 60, title, 18, 'F2', '1 1 1'));
  page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 74, subtitle, 8, 'F1', '0.86 0.9 0.95'));
}

function addFooter(page: PdfPage, totalPages: number) {
  page.commands.push(line(MARGIN, 34, PAGE_WIDTH - MARGIN, 34));
  page.commands.push(textLine(MARGIN, 20, 'Generated by SHIELD', 8, 'F1', MUTED));
  page.commands.push(textLine(PAGE_WIDTH - MARGIN - 56, 20, `Page ${page.pageNumber} of ${totalPages}`, 8, 'F1', MUTED));
}

function buildPdf(pages: PdfPage[]) {
  pages.forEach((page) => addFooter(page, pages.length));

  const objects: string[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    `<< /Type /Pages /Count ${pages.length} /Kids ${pages.map((_, index) => `${3 + index * 2} 0 R`).join(' ')} >>`,
  ];

  pages.forEach((page, index) => {
    const pageObjectNumber = 3 + index * 2;
    const contentObjectNumber = pageObjectNumber + 1;
    const stream = page.commands.filter(Boolean).join('\n');
    objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> /F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> >> >> /Contents ${contentObjectNumber} 0 R >>`);
    objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);
  });

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return pdf;
}

export function downloadTrooperDailiesCsv(entries: TrooperDailyReportEntry[], label = 'trooper-dailies') {
  const detailKeys = Array.from(new Set(entries.flatMap((entry) => Object.keys(entry.details || {}))))
    .filter((key) => key !== 'narrative')
    .sort();
  const headers = [
    'Date',
    'User',
    'Email',
    'Rank',
    'PE Number',
    'Badge',
    'Home District',
    'District Worked',
    'Duty Hours',
    'Special Status',
    'Narrative',
    ...detailKeys,
  ];
  const rows = entries.map((entry) => [
    entry.date,
    userName(entry),
    entry.user.email || '',
    entry.user.rank || '',
    entry.user.peNumber || '',
    entry.user.badgeNumber || '',
    entry.user.district || '',
    entry.districtWorked,
    entry.dutyHours,
    entry.specialStatus,
    entry.details?.narrative || '',
    ...detailKeys.map((key) => entry.details?.[key] || ''),
  ]);
  const csv = [headers, ...rows].map((row) => row.map(escapeCsv).join(',')).join('\n');
  downloadBlob(csv, 'text/csv;charset=utf-8', `${cleanFilePart(label)}.csv`);
}

export function downloadTrooperDailiesPdf(entries: TrooperDailyReportEntry[], label = 'trooper-dailies') {
  const pages: PdfPage[] = [];
  let page = newPage(1);
  pages.push(page);
  addHeader(page, 'Trooper Daily Reports', `${entries.length.toLocaleString()} report${entries.length === 1 ? '' : 's'} exported ${new Date().toLocaleString()}`);
  let y = PAGE_HEIGHT - 112;

  entries.forEach((entry) => {
    if (y < 96) {
      page = newPage(pages.length + 1);
      pages.push(page);
      addHeader(page, 'Trooper Daily Reports', `${entries.length.toLocaleString()} report${entries.length === 1 ? '' : 's'} exported ${new Date().toLocaleString()}`);
      y = PAGE_HEIGHT - 112;
    }

    page.commands.push(`${BORDER} RG 0.7 w ${MARGIN} ${y - 50} ${PAGE_WIDTH - MARGIN * 2} 58 re S`);
    page.commands.push(textLine(MARGIN + 10, y - 16, `${entry.date} - ${userName(entry)}`, 10, 'F2'));
    page.commands.push(textLine(MARGIN + 10, y - 31, `${entry.dutyHours} hrs | ${entry.districtWorked} | ${entry.specialStatus || 'None'}`, 8, 'F1', MUTED));
    page.commands.push(textLine(MARGIN + 10, y - 45, `Rank: ${entry.user.rank || 'N/A'}   PE: ${entry.user.peNumber || 'N/A'}   Badge: ${entry.user.badgeNumber || 'N/A'}   Home: ${entry.user.district || 'N/A'}`, 8, 'F1', MUTED));
    y -= 68;
  });

  if (entries.length === 0) {
    page.commands.push(textLine(MARGIN, PAGE_HEIGHT - 132, 'No Trooper Daily reports matched the selected filters.', 11, 'F1'));
  }

  downloadBlob(buildPdf(pages), 'application/pdf', `${cleanFilePart(label)}.pdf`);
}
